openapi: 3.0.3
info:
  title: API Municípios por UF
  version: 1.0.0
  description: API para listar municípios brasileiros por UF, com paginação e fallback de cache.
servers:
  - url: http://localhost/api
paths:
  /ufs/{uf}/municipios:
    get:
      summary: Lista municípios por UF
      parameters:
        - in: path
          name: uf
          required: true
          schema:
            type: string
            example: SP
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: per_page
          schema:
            type: integer
            default: 15
      responses:
        '200':
          description: Lista paginada de municípios
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        ibge_code:
                          type: string
                  total:
                    type: integer
        '503':
          description: Serviço indisponível (provider e cache falharam)
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
