name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports: [6379:6379]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, redis
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Run lint (phpcs)
        run: composer lint

      - name: Run static analysis (phpstan)
        run: composer stan

      - name: Run tests
        run: php artisan test --testsuite=Feature,Unit 